// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"edumeet/ent/badge"
	"edumeet/ent/predicate"
	"edumeet/ent/user"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BadgeUpdate is the builder for updating Badge entities.
type BadgeUpdate struct {
	config
	hooks    []Hook
	mutation *BadgeMutation
}

// Where appends a list predicates to the BadgeUpdate builder.
func (bu *BadgeUpdate) Where(ps ...predicate.Badge) *BadgeUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetName sets the "name" field.
func (bu *BadgeUpdate) SetName(s string) *BadgeUpdate {
	bu.mutation.SetName(s)
	return bu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (bu *BadgeUpdate) SetNillableName(s *string) *BadgeUpdate {
	if s != nil {
		bu.SetName(*s)
	}
	return bu
}

// SetSvg sets the "svg" field.
func (bu *BadgeUpdate) SetSvg(s string) *BadgeUpdate {
	bu.mutation.SetSvg(s)
	return bu
}

// SetNillableSvg sets the "svg" field if the given value is not nil.
func (bu *BadgeUpdate) SetNillableSvg(s *string) *BadgeUpdate {
	if s != nil {
		bu.SetSvg(*s)
	}
	return bu
}

// SetNbRequirementEvent sets the "nbRequirementEvent" field.
func (bu *BadgeUpdate) SetNbRequirementEvent(i int) *BadgeUpdate {
	bu.mutation.ResetNbRequirementEvent()
	bu.mutation.SetNbRequirementEvent(i)
	return bu
}

// SetNillableNbRequirementEvent sets the "nbRequirementEvent" field if the given value is not nil.
func (bu *BadgeUpdate) SetNillableNbRequirementEvent(i *int) *BadgeUpdate {
	if i != nil {
		bu.SetNbRequirementEvent(*i)
	}
	return bu
}

// AddNbRequirementEvent adds i to the "nbRequirementEvent" field.
func (bu *BadgeUpdate) AddNbRequirementEvent(i int) *BadgeUpdate {
	bu.mutation.AddNbRequirementEvent(i)
	return bu
}

// SetType sets the "type" field.
func (bu *BadgeUpdate) SetType(s string) *BadgeUpdate {
	bu.mutation.SetType(s)
	return bu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (bu *BadgeUpdate) SetNillableType(s *string) *BadgeUpdate {
	if s != nil {
		bu.SetType(*s)
	}
	return bu
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (bu *BadgeUpdate) AddUserIDs(ids ...string) *BadgeUpdate {
	bu.mutation.AddUserIDs(ids...)
	return bu
}

// AddUsers adds the "users" edges to the User entity.
func (bu *BadgeUpdate) AddUsers(u ...*User) *BadgeUpdate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return bu.AddUserIDs(ids...)
}

// Mutation returns the BadgeMutation object of the builder.
func (bu *BadgeUpdate) Mutation() *BadgeMutation {
	return bu.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (bu *BadgeUpdate) ClearUsers() *BadgeUpdate {
	bu.mutation.ClearUsers()
	return bu
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (bu *BadgeUpdate) RemoveUserIDs(ids ...string) *BadgeUpdate {
	bu.mutation.RemoveUserIDs(ids...)
	return bu
}

// RemoveUsers removes "users" edges to User entities.
func (bu *BadgeUpdate) RemoveUsers(u ...*User) *BadgeUpdate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return bu.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BadgeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BadgeUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BadgeUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BadgeUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bu *BadgeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(badge.Table, badge.Columns, sqlgraph.NewFieldSpec(badge.FieldID, field.TypeString))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Name(); ok {
		_spec.SetField(badge.FieldName, field.TypeString, value)
	}
	if value, ok := bu.mutation.Svg(); ok {
		_spec.SetField(badge.FieldSvg, field.TypeString, value)
	}
	if value, ok := bu.mutation.NbRequirementEvent(); ok {
		_spec.SetField(badge.FieldNbRequirementEvent, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedNbRequirementEvent(); ok {
		_spec.AddField(badge.FieldNbRequirementEvent, field.TypeInt, value)
	}
	if value, ok := bu.mutation.GetType(); ok {
		_spec.SetField(badge.FieldType, field.TypeString, value)
	}
	if bu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   badge.UsersTable,
			Columns: badge.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.RemovedUsersIDs(); len(nodes) > 0 && !bu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   badge.UsersTable,
			Columns: badge.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   badge.UsersTable,
			Columns: badge.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{badge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BadgeUpdateOne is the builder for updating a single Badge entity.
type BadgeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BadgeMutation
}

// SetName sets the "name" field.
func (buo *BadgeUpdateOne) SetName(s string) *BadgeUpdateOne {
	buo.mutation.SetName(s)
	return buo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (buo *BadgeUpdateOne) SetNillableName(s *string) *BadgeUpdateOne {
	if s != nil {
		buo.SetName(*s)
	}
	return buo
}

// SetSvg sets the "svg" field.
func (buo *BadgeUpdateOne) SetSvg(s string) *BadgeUpdateOne {
	buo.mutation.SetSvg(s)
	return buo
}

// SetNillableSvg sets the "svg" field if the given value is not nil.
func (buo *BadgeUpdateOne) SetNillableSvg(s *string) *BadgeUpdateOne {
	if s != nil {
		buo.SetSvg(*s)
	}
	return buo
}

// SetNbRequirementEvent sets the "nbRequirementEvent" field.
func (buo *BadgeUpdateOne) SetNbRequirementEvent(i int) *BadgeUpdateOne {
	buo.mutation.ResetNbRequirementEvent()
	buo.mutation.SetNbRequirementEvent(i)
	return buo
}

// SetNillableNbRequirementEvent sets the "nbRequirementEvent" field if the given value is not nil.
func (buo *BadgeUpdateOne) SetNillableNbRequirementEvent(i *int) *BadgeUpdateOne {
	if i != nil {
		buo.SetNbRequirementEvent(*i)
	}
	return buo
}

// AddNbRequirementEvent adds i to the "nbRequirementEvent" field.
func (buo *BadgeUpdateOne) AddNbRequirementEvent(i int) *BadgeUpdateOne {
	buo.mutation.AddNbRequirementEvent(i)
	return buo
}

// SetType sets the "type" field.
func (buo *BadgeUpdateOne) SetType(s string) *BadgeUpdateOne {
	buo.mutation.SetType(s)
	return buo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (buo *BadgeUpdateOne) SetNillableType(s *string) *BadgeUpdateOne {
	if s != nil {
		buo.SetType(*s)
	}
	return buo
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (buo *BadgeUpdateOne) AddUserIDs(ids ...string) *BadgeUpdateOne {
	buo.mutation.AddUserIDs(ids...)
	return buo
}

// AddUsers adds the "users" edges to the User entity.
func (buo *BadgeUpdateOne) AddUsers(u ...*User) *BadgeUpdateOne {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return buo.AddUserIDs(ids...)
}

// Mutation returns the BadgeMutation object of the builder.
func (buo *BadgeUpdateOne) Mutation() *BadgeMutation {
	return buo.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (buo *BadgeUpdateOne) ClearUsers() *BadgeUpdateOne {
	buo.mutation.ClearUsers()
	return buo
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (buo *BadgeUpdateOne) RemoveUserIDs(ids ...string) *BadgeUpdateOne {
	buo.mutation.RemoveUserIDs(ids...)
	return buo
}

// RemoveUsers removes "users" edges to User entities.
func (buo *BadgeUpdateOne) RemoveUsers(u ...*User) *BadgeUpdateOne {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return buo.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the BadgeUpdate builder.
func (buo *BadgeUpdateOne) Where(ps ...predicate.Badge) *BadgeUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BadgeUpdateOne) Select(field string, fields ...string) *BadgeUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Badge entity.
func (buo *BadgeUpdateOne) Save(ctx context.Context) (*Badge, error) {
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BadgeUpdateOne) SaveX(ctx context.Context) *Badge {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BadgeUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BadgeUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (buo *BadgeUpdateOne) sqlSave(ctx context.Context) (_node *Badge, err error) {
	_spec := sqlgraph.NewUpdateSpec(badge.Table, badge.Columns, sqlgraph.NewFieldSpec(badge.FieldID, field.TypeString))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Badge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, badge.FieldID)
		for _, f := range fields {
			if !badge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != badge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Name(); ok {
		_spec.SetField(badge.FieldName, field.TypeString, value)
	}
	if value, ok := buo.mutation.Svg(); ok {
		_spec.SetField(badge.FieldSvg, field.TypeString, value)
	}
	if value, ok := buo.mutation.NbRequirementEvent(); ok {
		_spec.SetField(badge.FieldNbRequirementEvent, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedNbRequirementEvent(); ok {
		_spec.AddField(badge.FieldNbRequirementEvent, field.TypeInt, value)
	}
	if value, ok := buo.mutation.GetType(); ok {
		_spec.SetField(badge.FieldType, field.TypeString, value)
	}
	if buo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   badge.UsersTable,
			Columns: badge.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.RemovedUsersIDs(); len(nodes) > 0 && !buo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   badge.UsersTable,
			Columns: badge.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   badge.UsersTable,
			Columns: badge.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Badge{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{badge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
