// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"edumeet/ent/eventdocument"
	"edumeet/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EventDocumentDelete is the builder for deleting a EventDocument entity.
type EventDocumentDelete struct {
	config
	hooks    []Hook
	mutation *EventDocumentMutation
}

// Where appends a list predicates to the EventDocumentDelete builder.
func (edd *EventDocumentDelete) Where(ps ...predicate.EventDocument) *EventDocumentDelete {
	edd.mutation.Where(ps...)
	return edd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (edd *EventDocumentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, edd.sqlExec, edd.mutation, edd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (edd *EventDocumentDelete) ExecX(ctx context.Context) int {
	n, err := edd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (edd *EventDocumentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(eventdocument.Table, sqlgraph.NewFieldSpec(eventdocument.FieldID, field.TypeString))
	if ps := edd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, edd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	edd.mutation.done = true
	return affected, err
}

// EventDocumentDeleteOne is the builder for deleting a single EventDocument entity.
type EventDocumentDeleteOne struct {
	edd *EventDocumentDelete
}

// Where appends a list predicates to the EventDocumentDelete builder.
func (eddo *EventDocumentDeleteOne) Where(ps ...predicate.EventDocument) *EventDocumentDeleteOne {
	eddo.edd.mutation.Where(ps...)
	return eddo
}

// Exec executes the deletion query.
func (eddo *EventDocumentDeleteOne) Exec(ctx context.Context) error {
	n, err := eddo.edd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{eventdocument.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (eddo *EventDocumentDeleteOne) ExecX(ctx context.Context) {
	if err := eddo.Exec(ctx); err != nil {
		panic(err)
	}
}
