{
 "title": "Edumeet",
 "time": { "from": "2025-01-05T00:09:07.126Z", "to": "2025-01-05T00:30:48.354Z" },
 "refresh": "10s",
 "panels": [
  { "title": "App Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"app_logs\"} | json"
    }
   ]
  },
  { "title": "Prometheus metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Login request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "login_attempts_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Event Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "event_attempts_total", "legendFormat": "__auto" }
   ]
  }
 ]
}